name: Test Workflow

on: 
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: test-pr
      run: |
	      echo ${{ github.head_ref }}
        echo ${{ github.ref_name }}