name: Test Workflow

on: 
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v6
      with:
        PATTERNS: |
          *
          **/*
          !*.md
          !**/*.md
    - name: only-markdown
      if: env.GIT_DIFF && github.event_name == 'pull_request'
      run: |
        echo ${{ github.event_name }}
        echo ${{ env.GIT_DIFF }}
        echo ${{ env.MATCHED_FILES }}