name: Test Workflow

on: 
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v6
    - name: test-pr
      run: |
        echo ${{ env.GIT_DIFF }}